language: python
python: "2.7"
install: pip install -r requirements.txt .
script: env DISPLAY=:0 nosetests tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3